name: flutter_inappwebview_web
description: A Flutter plugin that allows you to add an inline webview, to use an headless webview, and to open an in-app browser window.
version: 6.0.0-beta.5
homepage: https://inappwebview.dev/
repository: https://github.com/pichillilorenzo/flutter_inappwebview
issue_tracker: https://github.com/pichillilorenzo/flutter_inappwebview/issues

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3
  flutter_inappwebview_internal_annotations: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  # flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  generators:
    path: dev_packages/generators

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterInAppWebViewWebPlatform
        fileName: flutter_inappwebview.dart

  assets:
    - packages/flutter_inappwebview_web/assets/t_rex_runner/t-rex.html
    - packages/flutter_inappwebview_web/assets/t_rex_runner/t-rex.css
    - packages/flutter_inappwebview_web/assets/web/web_support.js

false_secrets:
  - /test_node_server/*.pem
  - /test_node_server/*.pfx